import { IFileList } from '../golden-test-helpers'

export const fileListLenient: IFileList = {
    valid: [
        'common/boolean-literals-1',
        'common/boolean-literals-2',
        'common/boolean-literals-3',
        'common/boolean-literals-4',
        'common/double-quoted-strings-1',
        'common/double-quoted-strings-2',
        //'common/double-quoted-strings-3',
        'common/double-quoted-string-w-backslash-1',
        'common/double-quoted-string-w-backslash-2',
        'common/double-quoted-string-w-backslash-3',
        'common/double-quoted-string-w-backslash-4',
        'common/double-quoted-string-w-backslash-5',
        'common/double-quoted-string-w-backslash-6',
        'common/explicit-null-literals-1',
        'common/floats-1',
        'common/integers-1',
        'common/single-quoted-strings-1',
        'common/single-quoted-strings-2',
        //'common/single-quoted-strings-3',
        'common/single-quoted-string-w-backslash-1',
        'common/single-quoted-string-w-backslash-2',
        'common/single-quoted-string-w-backslash-3',
        'common/single-quoted-string-w-backslash-4',
        'common/single-quoted-string-w-backslash-5',
        'common/single-quoted-string-w-backslash-6',
        'lenient/implicit-null-literal-1',
        'lenient/implicit-null-literal-2',
        'lenient/implicit-null-literal-3',
    ],
    invalid: [
        'common/bad-boolean-literals-1',
        'common/bad-boolean-literals-2',
        'common/bad-boolean-literals-3',
        'common/bad-boolean-literals-4',
        'common/bad-boolean-literals-5',
        'common/bad-double-quoted-string-1',
        'common/bad-double-quoted-string-2',
        'common/bad-double-quoted-string-3',
        'common/bad-double-quoted-string-4',
        'common/bad-double-quoted-string-5',
        'common/bad-explicit-null-literal-1',
        'common/bad-explicit-null-literal-2',
        'common/bad-explicit-null-literal-3',
        'common/bad-explicit-null-literal-4',
        'common/bad-single-quoted-string-1',
        'common/bad-single-quoted-string-2',
        'common/bad-single-quoted-string-3',
        'common/bad-single-quoted-string-4',
        'common/bad-single-quoted-string-5',
    ],
}
