name: Dependency Security

on:
    pull_request:
    push:
        branches: ['main']
    schedule:
        - cron: '0 2 * * 1' # weekly

permissions:
    contents: read

jobs:
    audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            # Install w/ scripts disabled to reduce supply-chain risk
            - run: npm ci --ignore-scripts

            # npm audit (fail on high/critical; adjust to your tolerance)
            - run: npm audit --omit=dev --audit-level=high
              continue-on-error: true # keep job going to run lockfile lint too

            # Lockfile lint: HTTPS registry only, no Git protocols, correct manager
            - run: npx --yes lockfile-lint \
                  --path package-lock.json \
                  --type npm \
                  --validate-https \
                  --allowed-hosts registry.npmjs.org \
                  --empty-hostname false \
                  --validate-integrity
