# .github/workflows/gitleaks.yml
name: Secret Scan (Gitleaks)

on:
    push:
    pull_request:
    schedule:
        - cron: '0 1 * * 1' # weekly

permissions:
    contents: read
    security-events: write # <-- needed to upload SARIF to the Security tab

jobs:
    gitleaks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout (full history for better scanning)
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # Run the scan (skip on forked PRs where secrets are not available)
            - name: Gitleaks scan
              if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork }}
              uses: gitleaks/gitleaks-action@v2
              continue-on-error: true # allow upload step to run even if leaks are found
              env:
                  # Only required for org repos; user repos can leave this empty
                  GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
              with:
                  args: >
                      detect --source . --no-git --redact
                      --verbose
                      --report-format sarif
                      --report-path gitleaks.sarif

            # Upload SARIF so findings appear under "Security > Code scanning alerts"
            - name: Upload SARIF to GitHub Security
              if: ${{ (github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork) && always() }}
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: gitleaks.sarif

            # Optional: make the skip explicit in logs for forked PRs
            - name: Skipped on forked PRs
              if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork }}
              run: echo "Skipping Gitleaks on forked PRs (no secrets available)."
