# .github/workflows/gitleaks.yml
name: Secret Scan (Gitleaks)

on:
    push:
    pull_request:
    schedule:
        - cron: '0 1 * * 1'

permissions:
    contents: read
    security-events: write # needed for SARIF upload

jobs:
    gitleaks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout (full history for better scanning)
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Gitleaks scan
              if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork }}
              uses: gitleaks/gitleaks-action@v2
              continue-on-error: true # allow next steps to run even if leaks found
              env:
                  GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # empty for user repos (ok)
              with:
                  # Write SARIF explicitly into the workspace
                  args: >
                      detect --source . --no-git --redact --verbose
                      --report-format sarif
                      --report-path ${{ github.workspace }}/gitleaks.sarif

            # (Optional) Inspect whether the file was created
            # - name: Debug: list files
            #   run: ls -la ${{ github.workspace }}

            - name: Upload SARIF to GitHub Security
              if: ${{ (github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork) && hashFiles('gitleaks.sarif') != '' }}
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: gitleaks.sarif

            - name: Skipped on forked PRs
              if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork }}
              run: echo "Skipping Gitleaks on forked PRs (no secrets available)."
