name: Dead-link Checker

on:
    workflow_dispatch:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]
    schedule:
        - cron: '0 4 * * 1' # run weekly on Mondays at 04:00 UTC

jobs:
    link-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Run lychee (check for dead links in README.md)
              uses: lycheeverse/lychee-action@v2.0.2
              with:
                  args: >
                      --verbose
                      --no-progress
                      --user-agent "Mozilla/5.0 (compatible; YINI-link-checker/1.0)"
                      --exclude '^https://www\.npmjs\.com/package/yini-parser$'
                      ./README.md
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
