name: Run Unit & Smoke Tests (fast)

on:
    pull_request: # PR:s **Pre-merge** (Good for fast feedback before merge. - Secrets: Not available for PRs from forks (by default).)
    workflow_dispatch: # allows manual run from GitHub UI

jobs:
    run-unit-n-smoke-tests:
        #    runs-on: ubuntu-latest
        #    runs-on: windows-latest
        # strategy:
        #     matrix:
        #         # Available GitHub-hosted runner types see:
        #         # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
        #         os: [ubuntu-latest, macos-latest, ubuntu-20.04, macos-11]
        # runs-on: ${{ matrix.os }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20' # adjust as needed

            - name: Print Node.js version
              run: node --version

            - name: Install dependencies (no scripts)
              run: npm ci --ignore-scripts # npm clean-install (installs without changing package-lock.json)

            - name: Typecheck
              run: npm run typecheck --if-present

            - name: Lint
              run: npm run lint --if-present

            - name: Build # So that dist/ gets updated too.
              run: npm run build

            - name: Run unit tests
              run: |
                  echo "Running test: ${{ github.event.inputs.testName }}"
                  npm run ci:test:unit

            - name: Run smoke tests
              run: |
                  echo "Running test: ${{ github.event.inputs.testName }}"
                  npm run ci:test:smoke
