name: All Test Suites (full)

on:
    push: # Any push. **Post-merge** (Good for deploy / publish / generate artifacts.)
        branches: ['main'] # To main (direct commits, or merges from PRs).
    workflow_dispatch: # allows manual run from GitHub UI

jobs:
    run-all-tests:
        #    runs-on: ubuntu-latest
        #    runs-on: windows-latest
        # strategy:
        #     matrix:
        #         # Available GitHub-hosted runner types see:
        #         # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
        #         os: [ubuntu-latest, macos-latest, ubuntu-20.04, macos-11]
        # runs-on: ${{ matrix.os }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20' # adjust as needed

            - name: Print Node.js version
              run: node --version

            - name: Install dependencies (no scripts)
              run: npm ci --ignore-scripts # npm clean-install (installs without changing package-lock.json)

            - name: Typecheck
              run: npm run typecheck --if-present

            - name: Lint
              run: npm run lint --if-present

            - name: Build # So that dist/ gets updated too.
              run: npm run build

            - name: Run all test suites
              run: |
                  echo "Running test: ${{ github.event.inputs.testName }}"
                  npm run ci:test
