{
    "_syntaxTree": [
        {
            "originLevel": 1,
            "chain": {
                "Section1": {
                    "bValue1": true,
                    "intValue": 1,
                    "Section11": {
                        "sValue": 11,
                        "Section111": {
                            "sValue": 111,
                            "intValue": 111
                        }
                    }
                }
            }
        },
        {
            "originLevel": 2,
            "chain": {
                "Section12": {
                    "sValue": 12
                }
            }
        },
        {
            "originLevel": 1,
            "chain": {
                "Section2": {
                    "sValue": 2,
                    "Section21": {
                        "sValue": 21,
                        "bValue": false,
                        "Section211": {
                            "sValue": 211,
                            "Section2111": {
                                "sValue": 2111
                            }
                        }
                    }
                }
            }
        },
        {
            "originLevel": 4,
            "chain": {
                "Section2112": {
                    "sValue": 2112,
                    "strValue": "test2112"
                }
            }
        },
        {
            "originLevel": 2,
            "chain": {
                "Section22": {
                    "bValue3": true,
                    "Section221": {
                        "sValue": 221
                    }
                }
            }
        },
        {
            "originLevel": 2,
            "chain": {
                "Section23": {
                    "bValue3": true
                }
            }
        }
    ]
}
